CREATE TABLE CARD
  (
    C_ID INT,
    L_ID INT,
    C_VERIFY INT,
    C_WORTH INT,
    C_TITLE VARCHAR2(4000) UNIQUE,
    C_DESCRIPTION VARCHAR2(4000),
    PRIMARY KEY(C_ID)
  );
/
CREATE SEQUENCE card_seq START WITH 1 INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER card_seq_trg BEFORE
  INSERT ON card FOR EACH ROW BEGIN IF :new.C_ID IS NULL THEN
  SELECT card_seq.NEXTVAL INTO :new.C_ID FROM dual;
END IF;
END;
/
CREATE OR REPLACE TRIGGER card2_seq_trg BEFORE
  INSERT ON card FOR EACH ROW BEGIN IF :new.C_ID = 0 THEN
  SELECT card_seq.NEXTVAL INTO :new.C_ID FROM dual;
END IF;
END;
/
COMMIT;