INSERT INTO CHART(B_ID,CHART_SUM,CHART_DATE) VALUES (1,100,SYSDATE);
INSERT INTO CHART(B_ID,CHART_SUM,CHART_DATE) VALUES (1,80,SYSDATE);
INSERT INTO CHART(B_ID,CHART_SUM,CHART_DATE) VALUES (1,40,SYSDATE);
INSERT INTO CHART(B_ID,CHART_SUM,CHART_DATE) VALUES (1,20,SYSDATE);
INSERT INTO CHART(B_ID,CHART_SUM,CHART_DATE) VALUES (1,0,SYSDATE);
/
COMMIT;