server:
  port: 0
spring:
    application:
        name: board-display
    datasource:
    tomcat:
      initial-size: 2
      
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true